### ISSUE TITLE
Can an include receive and work with an input parameter?

### ISSUE THREAD

**Issue by sgilligan** [reshape/include#22]
Can an include can receive an input parameter?  With the hello example, can I pass a name for the partial to say 'Hello from Fred!'

**Comment by sgilligan** [comment]
I have discovered the answer is no

**Comment by jescalan** [comment]
It isn't exactly no -- includes get all variables from their parent scope automatically. So if you had a couple partials you wanted to say hello to different people, you could do something like this:

```
// index.sgr
each(loop="name of ['john', 'sally']")
  include(src='say-hello.sgr)
```

```
// say-hello.sgr
p {{ name }}
```

And if you want a more complex, mixin-like functionality with lots of logic and arguments, you should use a local function that returns html, since javascript is very well-suited to handle heavy logic and variables and html is not - it was a conscious decision not to try to force these capabilities into html - only the most basic logic is covered.

**Comment by sgilligan** [comment]
ah .. now I get it. That will do the trick actually. I've also been playing with local functions returning html, and we of course get ES6 templating thrown in. The end result is a lot of power that I didn't really twig to when first looking at this.

**Comment by jescalan** [comment]
Haha awesome! Yeah full es6 as supported by node built in by default. You know I wouldn't give you anything less than MAX POWER Simon 😉

Another great option is to use [static rendered components](https://github.com/reshape/preact-components), which use jsx, and are pretty portable and also can be hydrated client side for data binding and such.

**Comment by sgilligan** [comment]
you're getting me in deeper now! nicely integrating my react stuff would be be amazing.

**Comment by jescalan** [comment]
https://github.com/static-dev/spike-static-components-example for a full example

**Comment by pellejacobs** [comment]
@jescalan It would be clean to pass parameters directly to a partial. Eg. if I wanted to pass in the button text and a link to a partial that prints a button: 

```html
<include src="advanced-button.html" text="Text on the button" link="http://example.com"></include>
```
Similar to how Handlebars handles partials: 

```
{{> shared.button text="Text on the button" }}
```

In some sense, this is possible by using your method as a hack: 

```html
<each loop="partial in [{ text: 'Text on the button', link: 'http://example.com' }]">
  <include src="advanced-button.html"></include>
</each>
```
and calling `partial.text` instead of `text` inside the partial. 

Is there a cleaner way of doing this?

Would you be willing to accept a PR for this functionality?

**Comment by jescalan** [comment]
No, because it is not a feature, it would be completely changing the behavior so that it was something different. I would totally accept a separate library that worked like this though! If I'm not mistaken, @calebeby is working on one right now if you wanted to help with it 😁
