### ISSUE TITLE
Relative paths are not well supported

### ISSUE THREAD

**Issue by msssk** [reshape/include#27]
Consider the following file structure:
```
views/
    app/
        view1.html
    components/
        cardList.html
    layout.html
```

If `app/view1` extends `layout.html` with `src="./layout.html` and `layout.html` includes `components/cardList.html` with `src="components/cardList.html"` then `ctx.filename` has the wrong value at [line 18](https://github.com/reshape/include/blob/8952512cd9a16a881bd6caedd791a1f4973b017c/lib/index.js#L18).

**Comment by jescalan** [comment]
Consider includes to be like macros -- they resolve in-place. This is why they inherit any variables that are in scope in their parent view, and don't need to be passed data. Because their behavior is built to be like this, this behavior is appropriate. Layouts resolve into their views. You'd expect the output of the `view1` template to be `view1.html` when compiled, the scope of the layout becomes the scope of the view, and includes are resolved relative to the view. So in order to include the component, you'd need to use `../components/cardList.html` in that case.

This behavior can be changed by setting a `root` to resolve paths from, which is a frequent choice for those using deeply nested structures like the one shown here.

I am very much open to a PR that would change this behavior, but its not going to be a priority for me to add personally. If you want to get your feet wet with contribution, I'd encourage you to give it a shot!

**Comment by msssk** [comment]
Thank you, this is very helpful to understand! (I am thinking about a PR to add some explanation of this to the readme...) It also brings to light other issues with my desired architecture that are causing me to re-evaluate.

Do you have any examples or advice for a project with some complexity? I'm working on a project that isn't huge, but it's big enough that I'd like the ability to have top-level views in `views` as well as sub-level views in folders within the `views` folder. I'd like to have multiple layouts in `views` that can be extended by top-level views or sub-views. I'd also like to have components/mixins in `views/components` that can easily be included in a view.

For now I am working with a structure like this:
```
views/
    components/
        componentA.html
        componentB.html
    subviews/
        view1.html
        view2.html
    layout.html
    layout2.html
```

**Comment by jescalan** [comment]
Hey sorry for the unacceptably late response here, but basically yeah, when a project is complex like this you can usually just set the root to `views` and reference everything from there, it shouldn't be an issue. How did it turn out?

**Comment by msssk** [comment]
Hi Jeff! Thanks for getting back. It works fine. It's a bit of a mental shift (and some resistance!) initially to realizing "hey, I can't use relative paths in my HTML files!". But I totally understand that it makes sense, and once I made the shift it was very simple and clear.

**Comment by jescalan** [comment]
Sorry about that, but I'm really glad it worked! I am very much open to a PR that would make relative imports more straightforward, and it's possible within the code, I just don't have the bandwidth right now to implement it myself : (
