### ISSUE TITLE
Ability to include non-parsed files

### ISSUE THREAD

**Issue by mrmlnc** [reshape/include#9]
Hello, @jescalan,

Do you have any plans to add the ability to include files without parsing, for example, SVG sprite or CSS?

```html
<head>
  <include src="build/styles/styles.css" raw></include>
</head>
<body>
  <include src="build/images/sprite.svg" raw></include>
</body>
```

Or I should to use `reshape/content` with my own functions?

**Comment by jescalan** [comment]
Hi there! Just responded to this same issue in the posthtml repo. It should already work for svgs, and for css files, just wrap them in a style tag 😁

**Comment by mrmlnc** [comment]
@jescalan, Sorry, I thought that both projects now live separately.

**Comment by jescalan** [comment]
It's ok, they are different questions for each project although some answers might be similar.

In the case of reshape, anything inside a `<style>` tag is parsed as plaintext because of the HTML spec, so it's not possible to do something like this:

```html
<style>
  <include src='whatever.css'>
</style>
```

I think by far the best solution in this instance is to use a `link` tag -- if you have a CDN, the hit to your initial load time will be very minimal and entirely nonexistent after it's cached by the browser. If that's still not acceptable, I think the best solution would be a separate plugin that included css files via a `style` tag specifically. Something like this perhaps:

```html
<include-css src='whatever.css'>
```

This would be a pretty simple plugin to build, if you are interested it would be a great place to start contributing 😉

**Comment by mrmlnc** [comment]
Thanks you for detailed answer 💪

**Comment by jescalan** [comment]
Hi, just an update, I'm going to build out this functionality now, it will probably be live by tomorrow! It's going to be a webpack-loader-style addition that allows users to fit a parser to a type of include. Stay tuned!
